### PR TITLE
fix: file attachments in chat failing with AI SDK URL validation error

### LINKED ISSUE #1155: Attaching documents don't work (anymore?) in Chat
### Bug description

When attaching an image or PDF to a chat message, an error is displayed in the UI and the message is not processed by the model. 

Image

### Operating system

macOS Tahoe 26.3.1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

- attach an image or PDF to a message,
- ask a question about it
- hit send

### Relevant log output

```shell
Error: URL scheme must be http or https, got data:
    at validateDownloadUrl (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:180350:11)
    at download (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:212411:3)
    at :5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:212449:83
    at Array.map (<anonymous>)
    at :5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:212448:22
    at downloadAssets (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:212777:33)
    at convertToLanguageModelPrompt (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:212520:34)
    at streamStep (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:217975:42)
    at async fn (:5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:218437:9)
    at async :5173/Users/fbricon/Dev/projects/kortex-hub/kortex/packages/main/dist/index.cjs:213440:24
```

### Additional context

It's unclear to me if this ever worked. @benoitf mentioned an AI SDK update might have broken it.

### PR DESCRIPTION
**Pull request by fbricon**
The AI SDK v6 rejects data: URLs in downloadAssets(), so pass raw base64
strings to the model instead. Also fix filename not persisting to DB by
using the correct FileUIPart property.

Additional improvements:
- Convert text-based files to text parts for broader model compatibility,
  using istextorbinary for filename and buffer-based detection
  (FileContentDetector)
- Show file type icons (Font Awesome via Icon component) for non-image
  attachments instead of blank rectangles
- Clear attachments from UI immediately on send instead of waiting for
  stream completion
- Graceful error handling for file read failures and malformed data URLs
- Restore attachments and input on send failure so users can retry

Screenshot 2026-04-02 at 11 44 25

Fixes #1155

### CODE REVIEW

**Comment by fbricon** [comment]
we'll need to provide a flag for providers supporting PDFs out of the box (like Gemini). When they don't (e.g. Ollama), we'll need to extract the text and inline it in the request.

File: packages/renderer/src/lib/chat/components/multimodal-input.svelte [hunk 1]
```diff
@@ -143,18 +143,16 @@ async function submitForm(): Promise<void> {
...
-
+  const files = attachments.map(attachment => ({
+    type: 'file' as const,
+    url: attachment.url,
+    filename: attachment.name,
+    mediaType: attachment.contentType!,
+  }));
   attachments = [];
 
+  await chatClient.sendMessage({ text, files });
```
[the remark this answers is not in the document]
Comment (fbricon) [reply packages/renderer/src/lib/chat/components/multimodal-input.svelte]: fixed

File: packages/renderer/src/lib/chat/components/multimodal-input.svelte [hunk 2]
```diff
@@ -143,18 +143,16 @@ async function submitForm(): Promise<void> {
...
-
+  const files = attachments.map(attachment => ({
+    type: 'file' as const,
+    url: attachment.url,
+    filename: attachment.name,
+    mediaType: attachment.contentType ?? 'application/octet-stream',
+  }));
   attachments = [];
 
+  await chatClient.sendMessage({ text, files });
```
[the remark this answers is not in the document]
Comment (fbricon) [reply packages/renderer/src/lib/chat/components/multimodal-input.svelte]: fixed

File: packages/main/src/chat/file-content-detector.spec.ts [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+import { describe, expect, it } from 'vitest';
+
+import { FileContentDetector } from './file-content-detector.js';
+
+describe('FileContentDetector', () => {
+  const detector = new FileContentDetector();
+  const textBuffer = Buffer.from('hello world');
+  const binaryBuffer = Buffer.from([0x80, 0x81, 0xff, 0xfe, 0x00, 0x01]);
+
+  describe('MIME type detection', () => {
```
Comment (gastoner) [inline packages/main/src/chat/file-content-detector.spec.ts]: Please avoid having multiple level of describes

File: packages/main/src/chat/file-content-detector.spec.ts [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+      'image/jpeg',
+      'audio/mpeg',
+      'video/mp4',
+      'application/pdf',
+    ])('should detect %s as binary', mimeType => {
+      expect(detector.isTextContent(mimeType, undefined, textBuffer)).toBe(false);
+    });
+  });
+
+  describe('file extension detection', () => {
```
Comment (gastoner) [inline packages/main/src/chat/file-content-detector.spec.ts]: Same here

File: packages/main/src/chat/file-content-detector.spec.ts [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+    it('should be case-insensitive for extensions', () => {
+      expect(detector.isTextContent('application/x-unknown', 'README.MD', textBuffer)).toBe(true);
+    });
+
+    it('should not match files without known extensions', () => {
+      expect(detector.isTextContent('application/x-unknown', 'data.xyz', binaryBuffer)).toBe(false);
+    });
+  });
+
+  describe('null-byte fallback', () => {
```
Comment (gastoner) [inline packages/main/src/chat/file-content-detector.spec.ts]: And here

File: packages/main/src/chat/chat-manager.spec.ts [hunk 6]
```diff
@@ -27,6 +31,13 @@ import type { ProviderRegistry } from '/@/plugin/provider-registry.js';
 
 import { ChatManager } from './chat-manager.js';
 
+vi.mock(import('node:fs/promises'), async importOriginal => {
+  const original = await importOriginal();
+  return {
+    ...original,
+    readFile: vi.fn(),
+  };
+});
```
Comment (gastoner) [inline packages/main/src/chat/chat-manager.spec.ts]: Nit: I think we can have only `vi.mock(import('node:fs/promises');` here

File: packages/main/src/chat/file-content-detector.spec.ts [hunk 7]
```diff
@@ -0,0 +1,117 @@
...
+
+import { FileContentDetector } from './file-content-detector.js';
+
+describe('FileContentDetector', () => {
+  const detector = new FileContentDetector();
+  const textBuffer = Buffer.from('hello world');
+  const binaryBuffer = Buffer.from([0x80, 0x81, 0xff, 0xfe, 0x00, 0x01]);
+
+  describe('MIME type detection', () => {
+    it.each(['text/plain', 'text/html', 'text/x-java-source', 'text/csv'])('should detect %s as text', mimeType => {
```
Comment (benoitf) [inline packages/main/src/chat/file-content-detector.spec.ts]: note: we use `test` not `it`

File: packages/main/src/chat/file-content-detector.ts [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+  private static readonly BINARY_MIME_PREFIXES = ['image/', 'audio/', 'video/'];
+
+  private static readonly BINARY_MIME_TYPES = new Set(['application/pdf', 'application/octet-stream']);
+
+  /**
+   * Determines whether a file should be sent as text content rather than a
+   * binary file part. Uses MIME type, file extension, and null-byte detection
+   * (in that order) to decide.
+   */
+  isTextContent(mediaType: string, filename: string | undefined, buffer: Buffer): boolean {
```
Comment (benoitf) [inline packages/main/src/chat/file-content-detector.ts:36]: question: can we reuse some existing npmjs libraries that would provide such detection / mimetypes etc ?

File: packages/main/src/chat/file-content-detector.spec.ts (hunk 7 above)
Comment (fbricon) [reply packages/main/src/chat/file-content-detector.spec.ts]: fixed

File: packages/main/src/chat/chat-manager.spec.ts (hunk 6 above)
Comment (fbricon) [reply packages/main/src/chat/chat-manager.spec.ts]: fixed

File: packages/main/src/chat/file-content-detector.spec.ts (hunk 3 above)
Comment (fbricon) [reply packages/main/src/chat/file-content-detector.spec.ts]: fixed

File: packages/main/src/chat/file-content-detector.spec.ts (hunk 4 above)
Comment (fbricon) [reply packages/main/src/chat/file-content-detector.spec.ts]: fixed

File: packages/main/src/chat/file-content-detector.spec.ts (hunk 5 above)
Comment (fbricon) [reply packages/main/src/chat/file-content-detector.spec.ts]: fixed

File: packages/main/src/chat/file-content-detector.ts (hunk 8 above)
Comment (fbricon) [reply packages/main/src/chat/file-content-detector.ts:36]: It's now using [istextorbinary](https://www.npmjs.com/package/istextorbinary). Its [Artistic-2.0](https://opensource.org/license/Artistic-2.0) license is compatible with Apache 2.0.
