### PR TITLE
fix: add persistence to the openai inference provider

### LINKED ISSUE #34: openai provider is not persistent over reboot
Since I need to save both baseURL + token, I could not copy paste the code from the gemini & github mcp, so the openai provider has no persistent over reboot

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #34

### CODE REVIEW

File: extensions/openai-compatible/src/openAI.ts [hunk 1]
```diff
@@ -36,13 +54,71 @@ export class OpenAI implements Disposable {
...
+    let raw: string | undefined;
+    try {
+      raw = await this.secrets.get(TOKENS_KEY);
+    } catch (err: unknown) {
+      console.error('openai: something went wrong while trying to get tokens from secret storage', err);
+    }
+    // if undefined return empty array
+    if (!raw) return [];
+    // split raw string by token separator
+    return raw.split(TOKEN_SEPARATOR).map(str => {
```
Comment (axel7083) [inline extensions/openai-compatible/src/openAI.ts:84]: I used the `separator` technique in other extensions, but for long term we should probably just `JSON.parse / JSON.stringify`
