### PR TITLE
fix: don't display flow runtime selector if there is a single one

### LINKED ISSUE #119: In flow creation, when only one flow provider, select automatically in combobox
In flow creation, when only one flow provider, select automatically in combobox

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #119

### CODE REVIEW

File: packages/renderer/src/lib/flows/FlowCreate.svelte [hunk 1]
```diff
@@ -28,6 +30,25 @@ let flowProviderConnectionKey: string | undefined = $state<string>();
 flowCreationStore.set(undefined);
 
 let hasInstalledFlowProviders = $state(window.hasInstalledFlowProviders());
+let showFlowConnectionSelector = $state(true);
+
+onMount(() => {
+  // If there is exactly one available flow connection across all providers,
```
Comment (benoitf) [inline packages/renderer/src/lib/flows/FlowCreate.svelte]: wondering why it's not using $derived as well
