### PR TITLE
fix(chat): change generate flow icon, align items

### LINKED ISSUE #228: replace export icon
today it's a plus, not easy to understand what it does

maybe use https://fontawesome.com/icons/file-export?f=classic&s=solid

### PR DESCRIPTION
**Pull request by simonrey1**
Screenshot 2025-09-04 at 10 35 44
Fixes #228

### CODE REVIEW

File: packages/renderer/src/lib/chat/components/messages/preview-message.svelte [hunk 1]
```diff
@@ -148,8 +147,7 @@ const tools: Array<DynamicToolUIPart> = message.parts.filter(part => part?.type
 										variant="ghost"
 										title={$isGooseCliToolInstalled? 'Export as Flow' : 'Install flow provider to enable save.'}
 									>
-										<PlusIcon size={14}>
-										</PlusIcon>
+										 <i class="fa-solid fa-file-export fa-2x" aria-hidden="true"></i>
```
Comment (benoitf) [inline packages/renderer/src/lib/chat/components/messages/preview-message.svelte]: we do use a svelte component:

```
<Fa icon={...}
```
