### PR TITLE
fix(chat): when MCP not installed invite user with link in toast

### LINKED ISSUE #209: Toast for required MCP server is not show anymore
Error: Suggested action What are the last 5 issues of Github repository podman-desktop/podman-desktop? requires MCP with id internal:123e4567-e89b-12d3-a456-426614172000:0 but it was not found.

### PR DESCRIPTION
**Pull request by simonrey1**
fixes #209 

https://github.com/user-attachments/assets/2fb51492-aaf4-4208-b894-5c8329035ef4

### CODE REVIEW

File: packages/renderer/src/lib/chat/components/McpsToInstallToast.svelte [hunk 1]
```diff
@@ -0,0 +1,31 @@
+<script lang="ts">
+import { faDownload } from '@fortawesome/free-solid-svg-icons';
+import type { components } from 'mcp-registry';
+import Fa from 'svelte-fa';
+
+import { handleNavigation } from '/@/navigation';
+import { NavigationPage } from '/@api/navigation-page';
+
+let { mcpsToInstall }: { mcpsToInstall: readonly components['schemas']['ServerDetail'][] } = $props();
```
Comment (axel7083) [inline packages/renderer/src/lib/chat/components/McpsToInstallToast.svelte]:
```suggestion
interface Props {
  mcpsToInstall: readonly components['schemas']['ServerDetail'][]
}

let { mcpsToInstall }: Props = $props();
```

File: packages/renderer/src/lib/chat/components/suggested-actions.svelte [hunk 2]
```diff
@@ -41,6 +43,60 @@ const suggestedActions = [
     action: 'What is the weather like in San Francisco?',
   },
 ];
+
+let onclick = async (suggestedAction: (typeof suggestedActions)[0]): Promise<void> => {
```
Comment (axel7083) [inline packages/renderer/src/lib/chat/components/suggested-actions.svelte]: why not using function format?
