### PR TITLE
fix: default model handling is broken 

### LINKED ISSUE #254: In Flow > Create, default selected model does not enable Generate button
In Flow > Create, default selected model does not enable Generate button

You have to select the model manually for the Generate button to be enabled again

Image

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #254 #255

### CODE REVIEW

File: packages/renderer/src/lib/models/models-utils.ts [hunk 1]
```diff
@@ -25,3 +26,6 @@ export function getModels(providerInfos: ProviderInfo[]): ModelInfo[] {
     [] as Array<ModelInfo>,
   );
 }
+export function getFirstModel(models: Array<ModelInfo>): ModelInfo | undefined {
+  return models && models.length > 0 ? models[0] : undefined;
```
Comment (simonrey1) [inline packages/renderer/src/lib/models/models-utils.ts:30]: suggestion: It takes an array of models, so getFirstModel could be equivalent to `models[0]`

Comment (simonrey1) [reply packages/renderer/src/lib/models/models-utils.ts:30]: https://github.com/kortex-hub/kortex/pull/272/files
