### PR TITLE
fix: handle workspace state

### LINKED ISSUE #1390: Workspace list does not retrieve the list of workspace state
### Bug description

the workspace list has its own store for handling workspace state 

### Operating system

Win11Pro

### Installation Method

None

### Version

0.0.3

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
To test:

- have a stopped workspace
- start Kaiden
- verify workspace page allows to start the workspace
- start the workspace
- restart kaiden
- verifies workspace page allows to stop the workspace
 
Fixes #1390

### CODE REVIEW

File: packages/renderer/src/stores/agent-workspaces.svelte.ts [hunk 1]
```diff
@@ -49,25 +51,44 @@ export const agentWorkspacesEventStore = new EventStore<AgentWorkspaceSummary[]>
...
+    return found ? updatedWorkspaces : workspaces;
+  });
+  return found;
+}
+
 export async function startAgentWorkspace(id: string): Promise<void> {
-  agentWorkspaceStatuses.set(id, 'starting');
+  if (!setWorkspaceState(id, 'starting')) {
+    throw new Error(`Invalid workspace id: ${id}`);
+  }
```
Comment (bmahabirbu) [inline packages/renderer/src/stores/agent-workspaces.svelte.ts:72]: Non-blocking: Maybe we can add a test for this?

```
  test('startAgentWorkspace should throw for unknown workspace id', async () => {                                                                                    
    await expect(startAgentWorkspace('nonexistent')).rejects.toThrow('Invalid workspace id: nonexistent');                                                           
  }); 

```

File: packages/renderer/src/stores/agent-workspaces.svelte.ts [hunk 2]
```diff
@@ -49,25 +51,44 @@ export const agentWorkspacesEventStore = new EventStore<AgentWorkspaceSummary[]>
...
     console.error('Failed to start agent workspace', error);
     throw error;
   }
 }
 
 export async function stopAgentWorkspace(id: string): Promise<void> {
-  agentWorkspaceStatuses.set(id, 'stopping');
+  if (!setWorkspaceState(id, 'stopping')) {
+    throw new Error(`Invalid workspace id: ${id}`);
+  }
```
Comment (bmahabirbu) [inline packages/renderer/src/stores/agent-workspaces.svelte.ts:86]: Non-blocking: Maybe we can also add a test for this too? 

```
  test('stopAgentWorkspace should throw for unknown workspace id', async () => {                                                                                     
    await expect(stopAgentWorkspace('nonexistent')).rejects.toThrow('Invalid workspace id: nonexistent');
  });  

```

**Review by bmahabirbu — APPROVED** [review]
Tested on fedora 42 LGTM! just a small non-blocker for additional test coverage but not necessary

**Review by MarsKubeX — APPROVED** [review]
LGTM. Tested on Mac.
