### PR TITLE
fix: auto select first model in flow create

### LINKED ISSUE #220: No model selected by default when Flow > Create
Image

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixed #220

### CODE REVIEW

File: packages/renderer/src/lib/chat/components/model-selector.svelte [hunk 1]
```diff
@@ -32,14 +32,18 @@ let groups: Map<string, Array<ModelInfo>> = $derived(
 );
 
 let open = $state(false);
+
+let usedValue = $derived(value ?? models[0]);
```
Comment (axel7083) [inline packages/renderer/src/lib/chat/components/model-selector.svelte:36]: This is probably not needed since you select the default in chat.svelte

Comment (jeffmaury) [reply packages/renderer/src/lib/chat/components/model-selector.svelte:36]: I moved it here so that it is reused
