### PR TITLE
fix: refresh RAG environmment on proper event

### LINKED ISSUE #1128: RAG environments are always listed as disconnected

### PR DESCRIPTION
**Pull request by jeffmaury**
To test:

- create a Milvus resource
- create a Rag environment based on this resource
- chck it is listed as Connected

Fixes #1128

### CODE REVIEW

File: packages/main/src/plugin/rag-environment-registry.ts [hunk 1]
```diff
@@ -187,17 +189,23 @@ export class RagEnvironmentRegistry {
...
+    if (ragConnection) {
+      const serverId = ragConnection.connection.mcpServer.serverId;
+      mcpServer = this.mcpManager.findMcpRemoteServer(
+        INTERNAL_PROVIDER_ID,
+        serverId,
+        ragConnection.connection.mcpServer.config.type,
+        ragConnection.connection.mcpServer.config.index,
+      );
+    }
+    if (
```
Comment (bmahabirbu) [inline packages/main/src/plugin/rag-environment-registry.ts:203]: could be simplified to `if (environment.mcpServer !== mcpServer) {` no?
