### PR TITLE
fix: hides new chat button when no provider connected

### LINKED ISSUE #1430: Sidebar and "New Chat" button visible when no provider connected
Image

### Bug description

The chat sidebar and 'New Chat' button are displayed when no AI model providers are connected. Since the application correctly identifies that no models are available ("No AI Models Available"), these navigation elements should be hidden.

### Operating system

all

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
Pre:
Image

Now:
Screenshot 2026-04-27 at 7 33 00

Closes #1430

### CODE REVIEW

File: packages/renderer/src/lib/chat/components/app-sidebar.svelte [hunk 1]
```diff
@@ -56,11 +58,14 @@ const context = useSidebar();
...
 					<TooltipContent side="bottom" align="end">New Chat</TooltipContent>
 				</Tooltip>
+			{/if}
 			</div>
 		</SidebarMenu>
 	</SidebarHeader>
-	<SidebarContent>
-		<SidebarHistory {chatId} />
-	</SidebarContent>
+	{#if hasModels}
```
Comment (fbricon) [inline packages/renderer/src/lib/chat/components/app-sidebar.svelte:65]: mmm this is debatable. I'd argue you should be able to see the existing chats even if you removed the provider. Now this might imply more work on the chat page, as you'd prolly need to make it model-free compatible to display the page properly. If it's not too much work, it might be nice to have, else we just keep hiding that page

Comment (jeffmaury) [reply packages/renderer/src/lib/chat/components/app-sidebar.svelte:65]: Let's make it a follow up issue as it would require more work post 0.2

**Review by jeffmaury — APPROVED** [review]

**Review by fbricon — APPROVED** [review]
