### PR TITLE
chore(ui): fix connect button alignment for welcome screen

### LINKED ISSUE #602: UI: 'Connect' button is misaligned for "Red Hat OpenShift AI" on the dashboard
On the main dashboard view, the "Connect..." button for the "Red Hat OpenShift AI" is misaligned.

### **Steps to Reproduce:**

1. Open the application in a state where no resources are configured.
2. Navigate to the "No AI Models Available" screen (the dashboard).
3. Observe the list of models available for connection, specifically the "Red Hat OpenShift AI" row.

Image

### PR DESCRIPTION
**Pull request by serbangeorge-m**
Assisted-by: Cursor
Closes #602

Screenshot 2025-11-19 at 1 24 39 PM

### CODE REVIEW

File: packages/renderer/src/lib/chat/components/NoModelsAvailable.svelte [hunk 1]
```diff
@@ -4,20 +4,36 @@ import ProviderInfoIcon from '/@/lib/preferences/ProviderInfoIcon.svelte';
 import { providerInfos } from '/@/stores/providers';
 </script>
 
+<style>
+  .provider-icon :global(img) {
```
Comment (simonrey1) [inline packages/renderer/src/lib/chat/components/NoModelsAvailable.svelte]: issue: please use tailwind classes instead of CSS <style>

Comment (serbangeorge-m) [reply packages/renderer/src/lib/chat/components/NoModelsAvailable.svelte]: @simonrey1 I think it is ok now
