### PR TITLE
fix: limit number of MCP servers displayed

### LINKED ISSUE #879: Search in the list of MCP server does not work
It's not possible anymore to search an MCP server in the list of MCP server.

Image

Error raised in the terminal:
`1:17:48 PM [main] [MCPSchemaValidator] Failed to validate data against schema 'ServerList' from 'https://registry.modelcontextprotocol.io'. [
  {
    instancePath: '/servers/0/server/repository',
    schemaPath: '#/components/schemas/Repository/required',
    keyword: 'required',
    params: { missingProperty: 'url' },
    message: "must have required property 'url'"
  }
]`

### PR DESCRIPTION
**Pull request by jeffmaury**
- Add registry.modelcontextprotocol.io as registry
- Go to the MCP server install tab
- Page should be fast to display

Fixes #879

### CODE REVIEW

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte [hunk 1]
```diff
@@ -68,20 +97,65 @@ const columns = [
...
+        Page {currentPage + 1} of {totalPages}
+      </span>
+      <button
+        class="px-3 py-1 rounded hover:bg-[var(--pd-button-hover-bg)] disabled:opacity-50 disabled:cursor-not-allowed"
+        onclick={nextPage}
+        disabled={currentPage >= totalPages - 1}
+        aria-label="Next page">
+        <Fa icon={faForward} />
+      </button>
+    </div>
```
Comment (simonrey1) [inline packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: suggestion(non-blocking): this seems to be the same pagination component as lines 108-128 above. Can you introduce a separate Svelte component for the pagination?

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte [hunk 2]
```diff
@@ -41,6 +43,33 @@ const servers: SelectableMCPRegistryServerDetailUI[] = $derived(
...
+// Pagination
+const PAGE_SIZE = 25;
+let currentPage = $state(0);
+
+const totalPages = $derived(Math.ceil(servers.length / PAGE_SIZE));
+const paginatedServers = $derived(servers.slice(currentPage * PAGE_SIZE, (currentPage + 1) * PAGE_SIZE));
+
+// Reset to first page when servers change
+$effect(() => {
+  servers;
```
Comment (simonrey1) [inline packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte:54]: question: is the goal of this line to add to the dependencies of the effect?

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte [hunk 3]
```diff
@@ -68,20 +97,65 @@ const columns = [
...
+      </button>
+      <span class="text-sm">
+        Page {currentPage + 1} of {totalPages}
+      </span>
+      <button
+        class="px-3 py-1 rounded hover:bg-[var(--pd-button-hover-bg)] disabled:opacity-50 disabled:cursor-not-allowed"
+        onclick={nextPage}
+        disabled={currentPage >= totalPages - 1}
+        aria-label="Next page">
+        <Fa icon={faForward} />
```
Comment (gastoner) [inline packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: Can we use `Icon` component from our ui lib ?

**Review by gastoner — COMMENTED** [review]
Same remarks as Simon

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 2 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte:54]: Yes

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 3 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: Would love but it does not seem to be exported !

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 1 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: Done in 497b814b409c222a84e18994eaddebfdd0ed09be

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte [hunk 4]
```diff
@@ -68,20 +96,29 @@ const columns = [
...
+{#if servers.length === 0}
+  {#if filter}
+    <FilteredEmptyScreen icon={McpIcon} kind="MCP Servers" bind:searchTerm={filter}/>
+  {:else}
+    <McpEmptyScreen />
+  {/if}
+{:else}
+  <div class="flex flex-col h-full w-full">
+    {#if totalPages > 1}
+      <PreviousNext onPrevious={previousPage} onNext={nextPage} previousDisabled={currentPage === 0} nextDisabled={currentPage >= totalPages - 1} title="Page {currentPage + 1} of {totalPages}"></PreviousNext>
```
Comment (simonrey1) [inline packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: suggestion(non-blocking): give more responsibility to the `PreviousNext` component

- condition `totalPages > 1` can be computed there to avoid duplication
- `title` can be computed in the component
- `previousDisabled` / `nextDisabled` can be computed there

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 3 above)
Comment (gastoner) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: You should be able to get it from `import { Icon } from '@podman-desktop/ui-svelte/icons';`

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 4 above)
Comment (simonrey1) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: @jeffmaury what do you think of this suggestion?

**Review by vancura — APPROVED** [review]

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 4 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: **thought:** that would tie the component to the notion pages which I tried to prevent but on the other side would increase code sharing. As it's an internal component, that might be an option

Comment (simonrey1) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: Cool, let me know if you will implement it or want a review as it

**Review by gastoner — APPROVED** [review]
LGTM then

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte (hunk 4 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: @simonrey1 updated the component, please review

File: packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte [hunk 5]
```diff
@@ -68,20 +96,29 @@ const columns = [
...
+  {:else}
+    <McpEmptyScreen />
+  {/if}
+{:else}
+  <div class="flex flex-col h-full w-full">
+    {#if totalPages > 1}
+      <PreviousNext onPrevious={previousPage} onNext={nextPage} currentPage={currentPage} totalPages={totalPages}></PreviousNext>
+    {/if}
 
     <Table
```
Comment (MarsKubeX) [inline packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]:
```suggestion
    <div class="flex">
      <Table
        kind="mcpServer"
        bind:this={table}
        data={paginatedServers}
        columns={columns}
        row={row}
        defaultSortColumn="Name">
      </Table>
     </div>
```
I have the horizontal scroll issue in this PR but not in main. if you wrap the Table in its own flex row div it gets the same shrink behavior it had in main

Comment (jeffmaury) [reply packages/renderer/src/lib/mcp/MCPServerListRegistryInstall.svelte]: Thanks for the tip @MarsKubeX

**Review by MarsKubeX — APPROVED** [review]
