### PR TITLE
fix: add information message to the create flow form

### LINKED ISSUE #221: enhance: add text explaining how to export a recipe on top of the Flow create page
add description on top of Flow create page explaining that there is another way using the export(+) button

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #221

image

### CODE REVIEW

File: packages/renderer/src/lib/flows/FlowCreate.svelte [hunk 1]
```diff
@@ -109,6 +110,12 @@ async function generate(): Promise<void> {
       <div class="px-5 pb-5 min-w-full">
       {#if hasInstalledFlowProvidersC}
           <div class="bg-[var(--pd-content-card-bg)] px-6 py-4">
+            <div class="flex flex-col">
+              <div>You can create a flow using this form by selecting a model, one or several tools (from MCP servers)
+                and specifying instructions.</div>
+              <div>A flow can also be created by exporting a chat session. All information's on this page will then automatically be filled.</div>
+              <div class="flex flex-row gap-1">The export feature in the chat window is available through the <PlusIcon size={14}/>icon</div>
```
Comment (simonrey1) [inline packages/renderer/src/lib/flows/FlowCreate.svelte:117]: suggestion: add class "items-center" to flex to align "+" icon
